insert into breed (breed_name) values ('Golden Retriever');
insert into breed (breed_name) values ('Labrador Retriever');
insert into breed (breed_name) values ('German Shepherd');
insert into breed (breed_name) values ('French Bulldog');
insert into breed (breed_name) values ('Bulldog');
insert into breed (breed_name) values ('Poodle');
insert into breed (breed_name) values ('Beagle');
insert into breed (breed_name) values ('Rottweiler');
insert into breed (breed_name) values ('Yorkshire Terrier');
insert into breed (breed_name) values ('Boxer');
insert into breed (breed_name) values ('Dachshund');
insert into breed (breed_name) values ('Siberian Husky');
insert into breed (breed_name) values ('Great Dane');
insert into breed (breed_name) values ('Doberman Pinscher');
insert into breed (breed_name) values ('Cavalier King Charles Spaniel');
insert into breed (breed_name) values ('Shih Tzu');
insert into breed (breed_name) values ('Boston Terrier');
insert into breed (breed_name) values ('Pomeranian');
insert into breed (breed_name) values ('Havanese');
insert into breed (breed_name) values ('Shetland Sheepdog');
insert into breed (breed_name) values ('Chihuahua');
insert into breed (breed_name) values ('Maltese');
insert into breed (breed_name) values ('Jack Russell Terrier');
insert into breed (breed_name) values ('Pug');
insert into breed (breed_name) values ('Border Collie');
insert into breed (breed_name) values ('Australian Shepherd');
insert into breed (breed_name) values ('Cocker Spaniel');
insert into breed (breed_name) values ('Pembroke Welsh Corgi');
insert into breed (breed_name) values ('Miniature Schnauzer');
insert into breed (breed_name) values ('Bichn Frise');
insert into breed (breed_name) values ('West Highland White Terrier');
insert into breed (breed_name) values ('Papillon');